export type BlogTag =
  | 'マドリー'
  | '選手列伝'
  | '戦術・歴史'
  | 'チャンピオンズリーグ';

export const ALL_TAGS: BlogTag[] = [
  'マドリー',
  '選手列伝',
  '戦術・歴史',
  'チャンピオンズリーグ',
];

export const postTags: Record<string, BlogTag[]> = {
  'di-stefano-european-cups': ['マドリー', 'チャンピオンズリーグ', '選手列伝'],
  'galacticos-light-and-shadow': ['マドリー', '戦術・歴史'],
  'zidane-cl-three-peat': ['マドリー', 'チャンピオンズリーグ'],
  'bernabeu-stadium-history': ['マドリー', '戦術・歴史'],
  'new-generation-2024': ['マドリー'],
  'best-eleven-maker-guide': ['戦術・歴史'],
  '4-3-3-evolution-real-madrid': ['マドリー', '戦術・歴史'],
  'benzema-ten-years': ['マドリー', '選手列伝'],
  'ronaldo-real-madrid-nine-years': ['マドリー', '選手列伝'],
  'champions-league-15-titles': ['マドリー', 'チャンピオンズリーグ'],
  'zidane-the-player': ['マドリー', '選手列伝'],
  'pressing-revolution': ['戦術・歴史'],
  'ronaldinho-the-joy': ['選手列伝'],
  'galacticos-2-beckham-to-kaka': ['マドリー', '戦術・歴史'],
  'total-football-cruyff': ['戦術・歴史'],
  'raul-the-legend': ['マドリー', '選手列伝'],
  'mourinho-real-madrid-era': ['マドリー', '戦術・歴史'],
  'sergio-ramos-legacy': ['マドリー', '選手列伝'],
  'ancelotti-magic-2022': ['マドリー', 'チャンピオンズリーグ', '戦術・歴史'],
  'modric-the-maestro': ['マドリー', '選手列伝'],
  'toni-kroos-the-metronome': ['マドリー', '選手列伝'],
  'roberto-carlos-the-cannon': ['マドリー', '選手列伝'],
  'iker-casillas-saint-iker': ['マドリー', '選手列伝'],
  'messi-barcelona-golden-age': ['選手列伝'],
  'buffon-the-wall': ['選手列伝'],
  'thierry-henry-arsenal-legend': ['選手列伝'],
  'van-basten-the-perfect-striker': ['選手列伝'],
  'pep-guardiola-tactical-revolution': ['戦術・歴史'],
  'ronaldinho-magic-years': ['選手列伝'],
  'xavi-iniesta-midfield-duo': ['選手列伝'],
  'zinedine-zidane-the-artist': ['選手列伝'],
  'paolo-maldini-the-eternal-captain': ['選手列伝'],
  'andrea-pirlo-the-conductor': ['選手列伝'],
  'samuel-eto-o-the-african-lion': ['選手列伝'],
  'gianluigi-buffon-the-last-wall': ['選手列伝'],
  'patrick-vieira-the-warrior': ['選手列伝'],
  'fernando-torres-anfield-hero': ['選手列伝'],
  'frank-lampard-the-goalscoring-midfielder': ['選手列伝'],
  'luka-modric-ballon-dor-2018': ['選手列伝'],
  'raul-gonzalez-club-legend': ['マドリー', '選手列伝'],
  'real-madrid-cl-2002-galacticos': ['マドリー', 'チャンピオンズリーグ'],
  'pepe-real-madrid-warrior': ['マドリー', '選手列伝'],
  'real-madrid-14th-cl-2022': ['マドリー', 'チャンピオンズリーグ'],
  'vinicius-junior-rise': ['マドリー', '選手列伝'],
  'ronaldo-nazario-the-phenomenon': ['選手列伝'],
  'liverpool-istanbul-miracle-2005': ['チャンピオンズリーグ', '戦術・歴史'],
  'guardiola-barcelona-tiki-taka': ['戦術・歴史'],
  'cristiano-ronaldo-juventus-era': ['選手列伝'],
  'netherlands-euro-1988-triumph': ['戦術・歴史'],
  'ronaldo-r9-barcelona-debut': ['選手列伝'],
  'ryan-giggs-manchester-united': ['選手列伝'],
  'chelsea-abramovich-era': ['戦術・歴史'],
  'ibrahimovic-the-unique': ['選手列伝'],
  'euro-2020-italy-resurrection': ['戦術・歴史'],
  'kaka-acmilan-golden-years': ['選手列伝', 'チャンピオンズリーグ'],
  'wayne-rooney-manchester-united-legacy': ['選手列伝'],
  'calcio-italy-serie-a-golden-age': ['戦術・歴史'],
  'beckham-real-madrid-impact': ['マドリー', '選手列伝'],
  'jose-mourinho-early-career': ['戦術・歴史', 'チャンピオンズリーグ'],
  'neymar-psg-and-brazil': ['選手列伝'],
  'arsenal-invincibles-2004': ['戦術・歴史'],
  'germany-2014-world-cup': ['戦術・歴史'],
  'claudio-ranieri-leicester-miracle': ['戦術・歴史'],
  'ronaldinho-barcelona-peak': ['選手列伝'],
  'paul-scholes-the-unsung-maestro': ['選手列伝'],
  'champions-league-greatest-comebacks': ['チャンピオンズリーグ', '戦術・歴史'],
  'luis-figo-real-madrid-transfer': ['マドリー', '選手列伝'],
  'eden-hazard-chelsea-years': ['選手列伝'],
  'real-madrid-la-decima-2014': ['マドリー', 'チャンピオンズリーグ'],
  'thierry-henry-world-cup-1998': ['選手列伝', '戦術・歴史'],
  'roberto-baggio-italy-1994': ['選手列伝'],
  'manchester-city-pep-dynasty': ['戦術・歴史'],
  'pirlo-italy-euro-2012': ['選手列伝', '戦術・歴史'],
  'sergio-aguero-manchester-city': ['選手列伝'],
  'maradona-hand-of-god-1986': ['選手列伝', '戦術・歴史'],
  'spain-2010-world-cup': ['戦術・歴史'],
  'messi-argentina-2022': ['選手列伝'],
  'france-2018-world-cup': ['戦術・歴史'],
  'brazil-1970-greatest-team': ['戦術・歴史'],
  'cristiano-ronaldo-portugal': ['選手列伝'],
  'eric-cantona-manchester-united': ['選手列伝'],
  'didier-drogba-chelsea': ['選手列伝'],
  'francesco-totti-roma': ['選手列伝'],
  'dennis-bergkamp-arsenal': ['選手列伝'],
  'steven-gerrard-liverpool': ['選手列伝'],
  'alan-shearer-premier-league': ['選手列伝'],
  'oliver-kahn-germany': ['選手列伝'],
  'michael-ballack-germany': ['選手列伝'],
  'clarence-seedorf-four-cls': ['選手列伝', 'チャンピオンズリーグ'],
  'dani-alves-most-decorated': ['選手列伝'],
  'philipp-lahm-germany': ['選手列伝'],
  'yaya-toure-man-city': ['選手列伝'],
  'filippo-inzaghi-goal-machine': ['選手列伝'],
  'rivaldo-brazil': ['選手列伝'],
  'ajax-football-factory': ['戦術・歴史'],
  'liverpool-klopp-era': ['戦術・歴史', 'チャンピオンズリーグ'],
  'atletico-madrid-colchoneros': ['戦術・歴史'],
  'catenaccio-italy-defense': ['戦術・歴史'],
  '1994-cl-milan-barca-final': ['チャンピオンズリーグ', '戦術・歴史'],
  'porto-cl-2004-miracle': ['チャンピオンズリーグ', '戦術・歴史'],
  'celtic-1967-lisbon-lions': ['チャンピオンズリーグ', '戦術・歴史'],
  'inter-treble-2010': ['チャンピオンズリーグ', '戦術・歴史'],
  'mbappe-real-madrid-arrival': ['マドリー', '選手列伝'],
  'erling-haaland-machine': ['選手列伝'],
  'jude-bellingham-midfield-genius': ['マドリー', '選手列伝'],
  'kevin-de-bruyne-passing-master': ['選手列伝'],
  'son-heungmin-asian-icon': ['選手列伝'],
  'greece-euro-2004-miracle': ['戦術・歴史'],
  'denmark-euro-1992-fairy-tale': ['戦術・歴史'],
  'croatia-2018-world-cup-run': ['選手列伝', '戦術・歴史'],
  'belgium-golden-generation': ['選手列伝', '戦術・歴史'],
  'var-technology-football': ['戦術・歴史'],
  'gianluigi-donnarumma-young-legend': ['選手列伝'],
  'virgil-van-dijk-defender-king': ['選手列伝'],
  'trent-alexander-arnold-revolution': ['選手列伝'],
  'sadio-mane-liverpool-senegal': ['選手列伝'],
  'mohamed-salah-egyptian-king': ['選手列伝'],
  'napoli-scudetto-2023': ['戦術・歴史'],
  'valencia-cl-2000-semifinal': ['チャンピオンズリーグ', '戦術・歴史'],
  'deportivo-real-madrid-comeback-2004': ['チャンピオンズリーグ', '戦術・歴史'],
  'euro-2020-italy-triumph': ['戦術・歴史'],
  'iceland-euro-2016-shock': ['戦術・歴史'],
  'zidane-coach-three-cl': ['マドリー', 'チャンピオンズリーグ', '戦術・歴史'],
  'manchester-city-treble-2023': ['チャンピオンズリーグ', '戦術・歴史'],
  'spain-golden-era-2008-2012': ['戦術・歴史'],
  'robert-lewandowski-bundesliga-king': ['選手列伝'],
  'ngolo-kante-the-engine': ['選手列伝'],
  'antoine-griezmann-world-class': ['選手列伝'],
  'manchester-united-treble-1999': ['チャンピオンズリーグ', '戦術・歴史'],
  'arsenal-wenger-philosophy': ['戦術・歴史'],
  'paulo-dybala-juventus-joya': ['選手列伝'],
  'jose-mourinho-vs-guardiola': ['戦術・歴史'],
  'borussia-dortmund-excitement': ['戦術・歴史'],
  'juventus-serie-a-dominance': ['戦術・歴史'],
  'cruyff-barcelona-coach': ['戦術・歴史'],
  'financial-fair-play-impact': ['戦術・歴史'],
  'thibaut-courtois-best-goalkeeper': ['マドリー', '選手列伝'],
  'red-bull-football-philosophy': ['戦術・歴史'],
  'romelu-lukaku-powerful-striker': ['選手列伝'],
  'frenkie-de-jong-midfield-art': ['選手列伝'],
  'victor-osimhen-african-power': ['選手列伝'],
  'ronaldinho-fc-barcelona-peak': ['選手列伝'],
  'bundesliga-history-overview': ['戦術・歴史'],
  'bayer-leverkusen-2024-title': ['戦術・歴史'],
  'florentino-perez-galacticos-strategy': ['マドリー', '戦術・歴史'],
  'premier-league-global-expansion': ['戦術・歴史'],
  'oliver-giroud-unsung-hero': ['選手列伝'],
  'xabi-alonso-midfield-master': ['選手列伝', '戦術・歴史'],
  'dimitar-berbatov-elegant-striker': ['選手列伝'],
  'gennaro-gattuso-warrior-spirit': ['選手列伝'],
  'la-liga-history-classic-era': ['戦術・歴史'],
  'champions-league-evolution': ['チャンピオンズリーグ', '戦術・歴史'],
  'peter-schmeichel-greatest-goalkeeper': ['選手列伝'],
  'roy-keane-iron-captain': ['選手列伝'],
  'paulo-maldini-dynasty': ['選手列伝', 'チャンピオンズリーグ'],
  'ligue-1-french-football-rise': ['戦術・歴史'],
  'serie-a-golden-age-1980s-1990s': ['戦術・歴史'],
  'carlos-alberto-brazil-1970': ['選手列伝', '戦術・歴史'],
  'marco-van-basten-perfection': ['選手列伝'],
  'steven-gerrard-one-man-army': ['選手列伝', 'チャンピオンズリーグ'],
  'real-sociedad-mid-table-beauty': ['戦術・歴史'],
  'world-cup-history-memorable-moments': ['戦術・歴史'],
  'atletico-madrid-simeone-era': ['戦術・歴史'],
  'neymar-barcelona-legacy': ['選手列伝'],
  'tactical-evolution-modern-football': ['戦術・歴史'],
  'youth-academies-world-football': ['戦術・歴史'],
  'porto-history-european-power': ['チャンピオンズリーグ', '戦術・歴史'],
  'marco-materazzi-and-zidane': ['選手列伝', '戦術・歴史'],
  'euro-history-from-1960': ['戦術・歴史'],
  'andres-iniesta-quiet-genius': ['選手列伝'],
  'luis-suarez-barcelona-striker': ['選手列伝'],
  'gabriel-batistuta-argentina-legend': ['選手列伝'],
  'david-villa-spain-striker': ['選手列伝'],
  'robinho-brazil-winger': ['選手列伝'],
  'pep-guardiola-player-years': ['戦術・歴史'],
  'world-cup-2006-germany': ['戦術・歴史'],
  'gareth-bale-real-madrid': ['マドリー', '選手列伝'],
  'vincent-kompany-defensive-leader': ['選手列伝'],
  'claudio-marchisio-juventus-maestro': ['選手列伝'],
  'manchester-city-abu-dhabi-era': ['戦術・歴史'],
  'world-cup-1998-france': ['戦術・歴史'],
  'ronaldo-nazario-comeback': ['選手列伝'],
};
