export type BlogTag =
  | 'レアル・マドリード'
  | 'バルセロナ'
  | '選手列伝'
  | '戦術・歴史'
  | 'チャンピオンズリーグ';

export const ALL_TAGS: BlogTag[] = [
  'レアル・マドリード',
  'バルセロナ',
  '選手列伝',
  '戦術・歴史',
  'チャンピオンズリーグ',
];

export const postTags: Record<string, BlogTag[]> = {
  'di-stefano-european-cups': ['レアル・マドリード', 'チャンピオンズリーグ', '選手列伝'],
  'galacticos-light-and-shadow': ['レアル・マドリード', '戦術・歴史'],
  'zidane-cl-three-peat': ['レアル・マドリード', 'チャンピオンズリーグ'],
  'bernabeu-stadium-history': ['レアル・マドリード', '戦術・歴史'],
  'new-generation-2024': ['レアル・マドリード'],
  'best-eleven-maker-guide': ['戦術・歴史'],
  '4-3-3-evolution-real-madrid': ['レアル・マドリード', '戦術・歴史'],
  'benzema-ten-years': ['レアル・マドリード', '選手列伝'],
  'ronaldo-real-madrid-nine-years': ['レアル・マドリード', '選手列伝'],
  'champions-league-15-titles': ['レアル・マドリード', 'チャンピオンズリーグ'],
  'zidane-the-player': ['レアル・マドリード', '選手列伝'],
  'pressing-revolution': ['戦術・歴史'],
  'ronaldinho-the-joy': ['バルセロナ', '選手列伝'],
  'galacticos-2-beckham-to-kaka': ['レアル・マドリード', '戦術・歴史'],
  'total-football-cruyff': ['戦術・歴史'],
  'raul-the-legend': ['レアル・マドリード', '選手列伝'],
  'mourinho-real-madrid-era': ['レアル・マドリード', '戦術・歴史'],
  'sergio-ramos-legacy': ['レアル・マドリード', '選手列伝'],
  'ancelotti-magic-2022': ['レアル・マドリード', 'チャンピオンズリーグ', '戦術・歴史'],
  'modric-the-maestro': ['レアル・マドリード', '選手列伝'],
  'toni-kroos-the-metronome': ['レアル・マドリード', '選手列伝'],
  'roberto-carlos-the-cannon': ['レアル・マドリード', '選手列伝'],
  'iker-casillas-saint-iker': ['レアル・マドリード', '選手列伝'],
  'messi-barcelona-golden-age': ['バルセロナ', '選手列伝'],
  'buffon-the-wall': ['選手列伝'],
  'thierry-henry-arsenal-legend': ['選手列伝'],
  'van-basten-the-perfect-striker': ['選手列伝'],
  'pep-guardiola-tactical-revolution': ['戦術・歴史'],
  'ronaldinho-magic-years': ['バルセロナ', '選手列伝'],
  'xavi-iniesta-midfield-duo': ['バルセロナ', '選手列伝'],
  'zinedine-zidane-the-artist': ['選手列伝'],
  'paolo-maldini-the-eternal-captain': ['選手列伝'],
  'andrea-pirlo-the-conductor': ['選手列伝'],
  'samuel-eto-o-the-african-lion': ['バルセロナ', '選手列伝'],
  'gianluigi-buffon-the-last-wall': ['選手列伝'],
  'patrick-vieira-the-warrior': ['選手列伝'],
  'fernando-torres-anfield-hero': ['選手列伝'],
  'frank-lampard-the-goalscoring-midfielder': ['選手列伝'],
  'luka-modric-ballon-dor-2018': ['選手列伝'],
  'raul-gonzalez-club-legend': ['レアル・マドリード', '選手列伝'],
  'real-madrid-cl-2002-galacticos': ['レアル・マドリード', 'チャンピオンズリーグ'],
  'pepe-real-madrid-warrior': ['レアル・マドリード', '選手列伝'],
  'real-madrid-14th-cl-2022': ['レアル・マドリード', 'チャンピオンズリーグ'],
  'vinicius-junior-rise': ['レアル・マドリード', '選手列伝'],
  'ronaldo-nazario-the-phenomenon': ['選手列伝'],
  'liverpool-istanbul-miracle-2005': ['チャンピオンズリーグ', '戦術・歴史'],
  'guardiola-barcelona-tiki-taka': ['バルセロナ', '戦術・歴史'],
  'cristiano-ronaldo-juventus-era': ['選手列伝'],
  'netherlands-euro-1988-triumph': ['戦術・歴史'],
  'ronaldo-r9-barcelona-debut': ['バルセロナ', '選手列伝'],
  'ryan-giggs-manchester-united': ['選手列伝'],
  'chelsea-abramovich-era': ['戦術・歴史'],
  'ibrahimovic-the-unique': ['選手列伝'],
  'euro-2020-italy-resurrection': ['戦術・歴史'],
  'kaka-acmilan-golden-years': ['選手列伝', 'チャンピオンズリーグ'],
  'wayne-rooney-manchester-united-legacy': ['選手列伝'],
  'calcio-italy-serie-a-golden-age': ['戦術・歴史'],
  'beckham-real-madrid-impact': ['レアル・マドリード', '選手列伝'],
  'jose-mourinho-early-career': ['戦術・歴史', 'チャンピオンズリーグ'],
  'neymar-psg-and-brazil': ['バルセロナ', '選手列伝'],
  'arsenal-invincibles-2004': ['戦術・歴史'],
  'germany-2014-world-cup': ['戦術・歴史'],
  'claudio-ranieri-leicester-miracle': ['戦術・歴史'],
  'ronaldinho-barcelona-peak': ['バルセロナ', '選手列伝'],
  'paul-scholes-the-unsung-maestro': ['選手列伝'],
  'champions-league-greatest-comebacks': ['チャンピオンズリーグ', '戦術・歴史'],
  'luis-figo-real-madrid-transfer': ['レアル・マドリード', '選手列伝'],
  'eden-hazard-chelsea-years': ['選手列伝'],
  'real-madrid-la-decima-2014': ['レアル・マドリード', 'チャンピオンズリーグ'],
};
