export interface Country {
  code: string;
  name: string;
  flag: string;
}

export const countries: Country[] = [
  // ヨーロッパ
  { code: 'AL', name: 'アルバニア',             flag: '🇦🇱' },
  { code: 'AD', name: 'アンドラ',               flag: '🇦🇩' },
  { code: 'AT', name: 'オーストリア',           flag: '🇦🇹' },
  { code: 'BY', name: 'ベラルーシ',             flag: '🇧🇾' },
  { code: 'BE', name: 'ベルギー',               flag: '🇧🇪' },
  { code: 'BA', name: 'ボスニア・ヘルツェゴビナ', flag: '🇧🇦' },
  { code: 'BG', name: 'ブルガリア',             flag: '🇧🇬' },
  { code: 'HR', name: 'クロアチア',             flag: '🇭🇷' },
  { code: 'CY', name: 'キプロス',               flag: '🇨🇾' },
  { code: 'CZ', name: 'チェコ',                 flag: '🇨🇿' },
  { code: 'DK', name: 'デンマーク',             flag: '🇩🇰' },
  { code: 'EE', name: 'エストニア',             flag: '🇪🇪' },
  { code: 'FI', name: 'フィンランド',           flag: '🇫🇮' },
  { code: 'FR', name: 'フランス',               flag: '🇫🇷' },
  { code: 'DE', name: 'ドイツ',                 flag: '🇩🇪' },
  { code: 'GR', name: 'ギリシャ',               flag: '🇬🇷' },
  { code: 'HU', name: 'ハンガリー',             flag: '🇭🇺' },
  { code: 'IS', name: 'アイスランド',           flag: '🇮🇸' },
  { code: 'IE', name: 'アイルランド',           flag: '🇮🇪' },
  { code: 'IT', name: 'イタリア',               flag: '🇮🇹' },
  { code: 'LV', name: 'ラトビア',               flag: '🇱🇻' },
  { code: 'LT', name: 'リトアニア',             flag: '🇱🇹' },
  { code: 'LU', name: 'ルクセンブルク',         flag: '🇱🇺' },
  { code: 'MT', name: 'マルタ',                 flag: '🇲🇹' },
  { code: 'MD', name: 'モルドバ',               flag: '🇲🇩' },
  { code: 'MC', name: 'モナコ',                 flag: '🇲🇨' },
  { code: 'ME', name: 'モンテネグロ',           flag: '🇲🇪' },
  { code: 'NL', name: 'オランダ',               flag: '🇳🇱' },
  { code: 'MK', name: '北マケドニア',           flag: '🇲🇰' },
  { code: 'NO', name: 'ノルウェー',             flag: '🇳🇴' },
  { code: 'PL', name: 'ポーランド',             flag: '🇵🇱' },
  { code: 'PT', name: 'ポルトガル',             flag: '🇵🇹' },
  { code: 'RO', name: 'ルーマニア',             flag: '🇷🇴' },
  { code: 'RU', name: 'ロシア',                 flag: '🇷🇺' },
  { code: 'RS', name: 'セルビア',               flag: '🇷🇸' },
  { code: 'SK', name: 'スロバキア',             flag: '🇸🇰' },
  { code: 'SI', name: 'スロベニア',             flag: '🇸🇮' },
  { code: 'ES', name: 'スペイン',               flag: '🇪🇸' },
  { code: 'SE', name: 'スウェーデン',           flag: '🇸🇪' },
  { code: 'CH', name: 'スイス',                 flag: '🇨🇭' },
  { code: 'TR', name: 'トルコ',                 flag: '🇹🇷' },
  { code: 'UA', name: 'ウクライナ',             flag: '🇺🇦' },
  { code: 'GB-ENG', name: 'イングランド',       flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿' },
  { code: 'GB-SCT', name: 'スコットランド',     flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿' },
  { code: 'GB-WLS', name: 'ウェールズ',         flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿' },
  { code: 'XK', name: 'コソボ',                 flag: '🇽🇰' },
  // 南米（欧州クラブで活躍した名手を含む）
  { code: 'AR', name: 'アルゼンチン',           flag: '🇦🇷' },
  { code: 'BR', name: 'ブラジル',               flag: '🇧🇷' },
  { code: 'CL', name: 'チリ',                   flag: '🇨🇱' },
  { code: 'CO', name: 'コロンビア',             flag: '🇨🇴' },
  { code: 'UY', name: 'ウルグアイ',             flag: '🇺🇾' },
  // アフリカ
  { code: 'CI', name: 'コートジボワール',       flag: '🇨🇮' },
  { code: 'CM', name: 'カメルーン',             flag: '🇨🇲' },
  { code: 'EG', name: 'エジプト',               flag: '🇪🇬' },
  { code: 'GH', name: 'ガーナ',                 flag: '🇬🇭' },
  { code: 'MA', name: 'モロッコ',               flag: '🇲🇦' },
  { code: 'NG', name: 'ナイジェリア',           flag: '🇳🇬' },
  { code: 'SN', name: 'セネガル',               flag: '🇸🇳' },
  // アジア
  { code: 'JP', name: '日本',                   flag: '🇯🇵' },
  { code: 'KR', name: '韓国',                   flag: '🇰🇷' },
];
